version: "3.6"

services:

  postgres:
    image: postgres:9.5.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DaVinci
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data